FROM python:3.6-alpine3.8 as builder
RUN apk update && apk add build-base
RUN pip install --install-option="--prefix=/install" django

FROM alpine:3.8
RUN apk update && apk add --no-cache dumb-init python3 && if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi
COPY --from=builder /install /usr
ENTRYPOINT ["/usr/bin/dumb-init"]
CMD ["python"]